export const cityListGermany = [
    { name: "Aachen", code: "AC" },
    { name: "Augsburg", code: "AUG" },
    { name: "Bamberg", code: "BAM" },
    { name: "Berlin", code: "BER" },
    { name: "Bielefeld", code: "BIE" },
    { name: "Bochum", code: "BO" },
    { name: "Bonn", code: "BN" },
    { name: "Bottrop", code: "BOT" },
    { name: "Brandenburg an der Havel", code: "BRB" },
    { name: "Bremen", code: "HB" },
    { name: "Bremerhaven", code: "BRV" },
    { name: "Chemnitz", code: "CHE" },
    { name: "Cottbus", code: "CB" },
    { name: "Darmstadt", code: "DA" },
    { name: "Dortmund", code: "DO" },
    { name: "Dresden", code: "DD" },
    { name: "Duisburg", code: "DU" },
    { name: "Düsseldorf", code: "DUS" },
    { name: "Erfurt", code: "EF" },
    { name: "Erlangen", code: "ER" },
    { name: "Essen", code: "E" },
    { name: "Flensburg", code: "FL" },
    { name: "Frankfurt am Main", code: "FRA" },
    { name: "Freiburg im Breisgau", code: "FR" },
    { name: "Fürth", code: "FÜ" },
    { name: "Gelsenkirchen", code: "GE" },
    { name: "Göttingen", code: "GÖ" },
    { name: "Hagen", code: "HA" },
    { name: "Halle (Saale)", code: "HAL" },
    { name: "Hamburg", code: "HH" },
    { name: "Hamm", code: "HAM" },
    { name: "Hannover", code: "H" },
    { name: "Heidelberg", code: "HD" },
    { name: "Heilbronn", code: "HN" },
    { name: "Herne", code: "HER" },
    { name: "Hildesheim", code: "HI" },
    { name: "Ingolstadt", code: "IN" },
    { name: "Jena", code: "J" },
    { name: "Kaiserslautern", code: "KL" },
    { name: "Karlsruhe", code: "KA" },
    { name: "Kassel", code: "KS" },
    { name: "Kiel", code: "KI" },
    { name: "Koblenz", code: "KO" },
    { name: "Köln", code: "CGN" },
    { name: "Krefeld", code: "KR" },
    { name: "Leipzig", code: "LEJ" },
    { name: "Leverkusen", code: "LEV" },
    { name: "Lübeck", code: "HL" },
    { name: "Ludwigshafen am Rhein", code: "LU" },
    { name: "Magdeburg", code: "MD" },
    { name: "Mainz", code: "MZ" },
    { name: "Mannheim", code: "MA" },
    { name: "Mönchengladbach", code: "MG" },
    { name: "München", code: "MUC" },
    { name: "Münster", code: "MS" },
    { name: "Neuss", code: "NE" },
    { name: "Nürnberg", code: "N" },
    { name: "Oberhausen", code: "OB" },
    { name: "Offenbach am Main", code: "OF" },
    { name: "Oldenburg", code: "OL" },
    { name: "Osnabrück", code: "OS" },
    { name: "Paderborn", code: "PB" },
    { name: "Pforzheim", code: "PF" },
    { name: "Potsdam", code: "P" },
    { name: "Regensburg", code: "R" },
    { name: "Reutlingen", code: "RT" },
    { name: "Rostock", code: "RO" },
    { name: "Saarbrücken", code: "SB" },
    { name: "Schwerin", code: "SN" },
    { name: "Siegen", code: "SI" },
    { name: "Solingen", code: "SG" },
    { name: "Stuttgart", code: "STR" },
    { name: "Trier", code: "TR" },
    { name: "Ulm", code: "UL" },
    { name: "Wiesbaden", code: "WI" },
    { name: "Wolfsburg", code: "WOB" },
    { name: "Wuppertal", code: "W" },
    { name: "Würzburg", code: "WÜ" },
    { name: "Zwickau", code: "Z" }
  ];
  